### PR TITLE
Supports config file

### PR DESCRIPTION
**Pull request by luiscoms**
This merge requests support to load config file by profile.

It loads ` "config/{profile}.yml"` file by default.
File path can be changed by setting `CONFIG_FILE_PATH` environment variable.

All configuration will be merged at de end.

### CODE REVIEW

**Comment by amenezes** [comment]
Hello @luiscoms,

First, thanks for your time to help on improvements in the `config-client`.

I don't know, at first, if bring an option to manage configuration locally it's a good choice. I think this breaks a bit the [externalized configuration](https://microservices.io/patterns/externalized-configuration.html) logic. This has already briefly been discussed in another [issue](https://github.com/amenezes/config-client/issues/19).

Originally I imagine that all we need it's to have a minimal configuration locally, just the necessary to contact the spring cloud config server and after recovering the configuration initialize the application properly. 

What do you think about? Are there any use cases that you would like to cover?

**Comment by luiscoms** [comment]
Hi @amenezes, 

This pull request cover the fail of config server and supports a default config that can be overridden by server config, just like spring boot does.

**Comment by luiscoms** [comment]
Any considerations?

**Comment by amenezes** [comment]
@luiscoms,

Could you explain me a little more about this feature and your needs?

There's some advantage in this approach over use, for example, of [dynaconf](https://dynaconf.readthedocs.io/en/latest/) or the [configparser](https://docs.python.org/3/library/configparser.html) for manage local configurations?

**Comment by luiscoms** [comment]
Hi, the pull request allows to load config file if exists and merge with cloud config.
I want to use config client to load both configs

**Comment by amenezes** [comment]
For now this issue will marked as invalid and closed. Maybe in the future we can reevaluate.

**Pull request closed without merging**
