### PR TITLE
Change logging to logger

### PR DESCRIPTION
**Pull request by luiscoms**
In order to log on `config` module instead of `root` logger, This pull request replace logging by logger

### CODE REVIEW

**Comment by amenezes** [comment]
@luiscoms,

Could you put the code snippet below in `config/__init__.py` file and change the calls for the logger?

```python
# config/__init__.py
logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())
```

```python
# For example: config/auth.py
# but all files that use logging must be changed to logger

# from
logging.info("Access token successfully obtained.")
# to
logger.info("Access token successfully obtained.")
```

**Comment by luiscoms** [comment]
Hi @amenezes,

I did the update, but change this cause that logger name is always 'config', not 'config.spring'

**Comment by amenezes** [comment]
Yes. It's because of the name of the `__name__` module. It is useful if in your application, for example, you want to disable library log messages. We can change to `config-client` what do you think?

**Comment by luiscoms** [comment]
Any other considerations?

**Pull request merged**
