### PR TITLE
Pass non init args to request

### PR DESCRIPTION
**Pull request by luiscoms**
This pull request improves `config_client` decorator passing args to `get_config` method.

```python
# app_name is a class init param
@config_client(app_name='awesome-app')  
def foo(client):
   return client

# timeout isn't a class init param, so this will be passed to get_config
@config_client(timeout=5)
def foo(client):
   return client

```

### CODE REVIEW

**Comment by luiscoms** [comment]
Hi @amenezes did you have any consideration?

**Comment by amenezes** [comment]
Good job @luiscoms :clap: 

I'm working in a improvement to release on the version `0.10.0` and probably I'will merge this PR with this release. I notify you when the work done.

Thanks.

> A single observation try fix the conflict being reported, please.

**Comment by luiscoms** [comment]
Hi @amenezes the tests are passing but there is an error on ci

**Comment by amenezes** [comment]
@luiscoms,

Looks like there's been a change in Travis CI. see the message:

```txt
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
```

Don't worry. When I merge I make the correction.

**Comment by luiscoms** [comment]
Hi @amenezes , when you intend to do this merge?

**Comment by luiscoms** [comment]
Hi @amenezes , some updates?

**Pull request merged**
