### PR TITLE
Tests for array values

### LINKED ISSUE #45: Get array value does not work on version 1.0.0
### Platform

All platforms

### Steps to Reproduce

After 1.0.0, `client.get` method does not retrieve array values.

Setting a config like this

```yml
example:
    - 1
    - 2
```

When I run `config.get('example')` #

### Expected Result

Prior 1.0.0

Results were

```python
> client.get('example')
[1, 2]
```

### Actual Result

After 1.0.0

Results are empty string

```python
> client.get('example')
''
```

#### PS: 

Running `client.get('example[0]')` return first value, but It's not useful because I don't know how many values are configured

```python
> client.get('example[0]')
1
```

### PR DESCRIPTION
**Pull request by luiscoms**
This Pull request have tests for fix #45

### CODE REVIEW

**Comment by amenezes** [comment]
@luiscoms,

The version 1.0.2 works partially with nested list settings.

But as you noted there are cases where there is still inconsistency in merging the settings. I believe that with a new fix the problem has been solved.

Could you try the version 1.0.3a0 - `pip install 'config-client[cli]'==1.0.3a0` and check if the problem was resolved. If you preferer test locally could you check branch rl-1.0.3 and make some requests for local config-server.

To start the config-server run: `docker-compose up -d` and after some seconds can you use the CLI to query config, for example:

```bash
# show all config from simpleweb000 on development profile
python -m config client simpleweb000 --all -v

# filter for some config
python -m config client simpleweb000 first.second_3 -v

python -m config client simpleweb000 example -v

python -m config client simpleweb000 examples -v
```

**Comment by amenezes** [comment]
@luiscoms,

I added some more tests to array values in the file [test_config.py](https://github.com/amenezes/config-client/blob/master/tests/unit/test_config.py). Could you added the entries that you entered in this PR in the related file?

**Comment by amenezes** [comment]
Ok @luiscoms. Could you provide some more examples in the [test_config.py](https://github.com/amenezes/config-client/blob/master/tests/unit/test_config.py), as the example below:

```python
@pytest.mark.parametrize(
    "data, expected",
    [
      ...
      (
          {"examples.three.one[0]": "one", "examples.three.one[1]": "thow"}, # data
          {"examples": {"three": {"one": ["one", "thow"]}}}, # expected
      )
    ]
)
def test_to_dict(data, expected):
    assert to_dict(data) == expected
```

**Comment by luiscoms** [comment]
I'v tested with version `1.0.3`, and it was fixed

**Pull request closed without merging**
